import React from "react";
import Head from "next/head";

import { ImInstagram } from "react-icons/im";
import { useRouter } from "next/router";
import Link from "next/link";
// import Image from "next/image";

const ModelList = ({ title, category, modelList }) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.premierartists.com/css/images/favicon.png"
          type="image/png"
        ></link>
      </Head>

      <div>
        <header className=" pt-8 items-center justify-center">
          <div className="text-center ">
            <Link href="/">
              <div className=" bg-[url('/logo.svg')] w-[10.5em] text-[80%] h-[2.5em] bg-no-repeat bg-[50%] inline-block md:text-[100%]"></div>
            </Link>
          </div>
        </header>

        <article>
          <section className="px-8 mx-auto  text-center ">
            <div className=" pt-[0.7rem] pb-8  ">
              <h3 className=" text-[1em] tracking-[0.1em] font-normal md:text-xl">
                {category}
              </h3>
            </div>
          </section>

          <section className="px-8 mx-auto  text-center md:max-w-[68rem]">
            <div className=" grid grid-cols-2 text-center md:grid-cols-4">
              {modelList?.map(({ id, picture, link, name, followers, bio }) => {
                return (
                  <div className=" m-[5px] md:m-0 md:mr-5 " key={id}>
                    <div className=" relative">
                      <div
                        onClick={() => {
                          router.push(`/${id}`);
                        }}
                      >
                        <div>
                          {" "}
                          <img src={picture} alt="image" />
                        </div>

                        <div className=" absolute cursor-pointer flex flex-col inset-0 bg-[url('/hover.png')] text-white opacity-0 transition-opacity hover:opacity-100">
                          <div className=" absolute w-full h-full">
                            <div className=" relative border-b border-b-white  h-1/2 top-0 text-base">
                              <div className=" relative text-center px-[10px] top-1/2 -translate-y-1/2">
                                <i>
                                  {" "}
                                  <ImInstagram className="inline pr-1 text-[26px]" />
                                </i>

                                {followers}
                              </div>
                            </div>
                            <div className="top-1/2 h-1/2">
                              <div className=" relative px-[10px] top-1/2 -translate-y-1/2">
                                {bio}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className=" mb-2 pt-2 pb-2 text-[10px] max-h-8">
                      {name}
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        </article>
      </div>
    </>
  );
};

export default ModelList;
