import React, { useRef } from "react";
import Head from "next/head";

import MySlider from "@/components/MySlider";
import Link from "next/link";
// import Image from "next/image";

const grid = [
  {
    id: "1",
    picture: "/images/ashu1.jpg",
  },
  {
    id: "2",
    picture: "/images/ashu2.jpg",
  },
  {
    id: "3",
    picture: "/images/ashu3.jpg",
  },
  {
    id: "4",
    picture: "/images/ashu4.jpg",
  },
  {
    id: "5",
    picture: "/images/ashu5.jpg",
  },
  {
    id: "6",
    picture: "/images/ashu6.jpg",
  },
  {
    id: "7",
    picture: "/images/ashu7.jpg",
  },
  {
    id: "8",
    picture: "/images/ashu8.jpg",
  },
  {
    id: "9",
    picture: "/images/ashu9.jpg",
  },
];

const adesuwa = () => {
  const divRef = useRef(null);
  const scrollToBio = (e) => {
    e.preventDefault();
    divRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };
  return (
    <>
      <Head>
        <title>Adesuwa| Premier Artists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>

      <article>
        <section className=" mx-auto pt-12 px-8 max-w-[68rem]">
          <div className=" mr-[14.25px] text-center pb-4 font-[130%]">
            <h2 className=" text-[35.2px] leading-[120%] tracking-[0.16em]">
              <Link href="/artist">ADESUWA</Link>
            </h2>
          </div>

          <div className=" text-center px-8 text-[0.8em] md:text-base md:tracking-[0.07em]">
            <ul className=" flex flex-row justify-center">
              <li className=" px-[0.4rem] md:px-4">
                <Link href="/adesuwa">PORTFOLIO</Link>
              </li>
              <li className="px-[0.4rem] md:px-4 profile-bio-link ">
                <Link href="" onClick={scrollToBio}>
                  BIO
                </Link>
              </li>
            </ul>
          </div>
        </section>

        {/* ... Slider ... */}

        <div className="pt-4 ">
          <MySlider />

          <section className=" max-w-[68rem] px-8 pt-8 mx-auto">
            <ul className=" text-center  text-[0.8em] italic tracking-[0.05em] flex flex-row justify-center md:text-[1em]">
              <li className=" px-[0.4rem]">
                Height
                <em>5'10''</em>
              </li>

              <li className="px-[0.4rem]">
                Bust
                <em>31'''</em>
              </li>
              <li className="  px-[0.4rem]">
                Waist
                <em> 31''</em>
              </li>
              <li className="  px-[0.4rem]">
                Hips
                <em> 34''</em>
              </li>
              <li className="  px-[0.4rem]">
                Shoe
                <em>6½</em>
              </li>
              <li className="  px-[0.4rem]">
                Hair
                <em>BROWN</em>
              </li>
              <li className=" px-[0.4rem]">
                Eyes
                <em>BROWN</em>
              </li>
            </ul>
          </section>
        </div>

        {/* ..... Portfolio Images ..... */}

        <div>
          <div className=" max-w-[68rem] mx-auto px-8 pt-8 ">
            <div className="border-t border-t-black "></div>
            <div></div>
          </div>

          <section className=" max-w-[68rem] px-8 pt-8 pb-[0.4rem] -mb-8 mx-auto ">
            <div className=" grid grid-cols-3 md:grid-cols-6">
              {grid.map(({ id, picture }) => {
                return (
                  <div key={id} className=" pb-[15px] mr-[15px]">
                    <div className="relative">
                      <img src={picture} />
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        </div>

        {/* .....  BIO SECTION ..... */}

        <div>
          <div className=" max-w-[68rem] px-8 pt-8 mx-auto">
            <div className=" border-t border-t-black"></div>
          </div>

          <section className="max-w-[68rem] px-8 pt-8 mx-auto profile-bio">
            <div ref={divRef}>
              <p className=" text-[1.1em] tracking-[0.07em] text-center leading-[150%]">
                Dubbed by i-D Magazine as one who has “captured fashion’s
                imagination.” ADESUWA represents the epitome of a new generation
                of models who seek to vocalize the deep layers of culture,
                history, and societal impact embodied by the fashion industry.
                Of Chinese, Nigerian, and Thai descent, Adesuwa initially
                entered the modeling world with an intention to earn money for a
                NASA internship. Her first big break arrived when she opened the
                Coach Spring/Summer 2018 show, a feat which earned her much
                momentum from the who’s-who of today’s top fashion houses. Soon,
                campaigns for Alexander Wang, Bottega Veneta, Chanel, Dior, Marc
                Jacobs, Vera Wang, and Versace became part of her repertoire,
                alongside covers for Numero, i-D, New York Times Style and
                editorials for multiple editions of Vogue, Harper’s Bazaar, CR
                Fashion Book, AnOther, Dazed, and many more. As notable global
                brands gradually became significant supporting forces behind her
                career, Adesuwa decided to utilize the new relationships
                cultivated within this field to amplify other pertinent issues.
                As her career ascended, Adesuwa’s creative potential has also
                extended into new heights: since 2017, she has penned think
                pieces for The Guardian on diversity issues within fashion,
                directed short films for LOVE magazine, and became Contributing
                Editor for i-D. In 2019, the British Fashion Council recognized
                her as one of the leading Creatives of the “NEW WAVE,” and she
                was also nominated for The Fashion Awards’ “Model of the Year”
                award. Currently, Adesuwa works diligently on preserving African
                culture and promoting its legacy to the world, with numerous
                projects in the works simultaneously to achieve her vision. As
                she stated to i-D, “I want to have a summit with all the coolest
                Africans from around the world, I want people to come together –
                everyone thinks they’re alone — but I want to bring everyone
                together and make a plan and help our continent.”
              </p>
            </div>
          </section>
        </div>
      </article>
    </>
  );
};

export default adesuwa;
