import Head from "next/head";
import Main from "@/components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Premier Artists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.premierartists.com/css/images/favicon.png"
          type="image/png"
        ></link>
      </Head>
      <Main />
    </>
  );
}
